apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: demo-app

spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - name: nginx 
      containerPort: 80


kubectl apply -f firstpod.yml

## To expose pod - need to create service 